// <auto-generated />
namespace marshall_clio_audio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Audio_auth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Audio_auth));
        
        string IMigrationMetadata.Id
        {
            get { return "201712052251009_Audio_auth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
